# Решение транспортной задачи
###### Вариант 17

In [1]:
import time
from cvxopt.modeling import variable, op
'''100 150 150 100 300
50 3 4 5 4 1
100 1 2 7 1 5
150 4 6 6 3 7
100 2 7 4 7 2
200 3 8 9 4 5'''
start = time.time()
x = variable(25, "x")
z = (3*x[0]+4*x[1]+5*x[2]+4*x[3]+1*x[4]+1*x[5]+2*x[6]+7*x[7]+1*x[8]+5*x[9]+4*x[10]+6*x[11]+6*x[12]+3*x[13]+7*x[14]+2*x[15]+7*x[16]+4*x[17]+7*x[18]+2*x[19]+3*x[20]+8*x[21]+9*x[22]+4*x[23]+5*x[24])
mass1 =(x[0]+x[1]+x[2]+x[3]+x[4]==50)
mass2 =(x[5]+x[6]+x[7]+x[8]+x[9]==100)
mass3 =(x[10]+x[11]+x[12]+x[13]+x[14]==150)
mass4 =(x[15]+x[16]+x[17]+x[18]+x[19]==100)
mass5 =(x[20]+x[21]+x[22]+x[23]+x[24]==200)
mass6 =(x[0]+x[5]+x[10]+x[15]+x[20]<=100)
mass7 =(x[1]+x[6]+x[11]+x[16]+x[21]<=150)
mass8 =(x[2]+x[7]+x[12]+x[17]+x[22]<=150)
mass9 =(x[3]+x[8]+x[13]+x[18]+x[23]<=100)
mass10 =(x[4]+x[9]+x[14]+x[19]+x[24]<=300)

x_non_negative = (x>=0)
problem = op(z,[mass1,mass2,mass3,mass4,mass5,mass6,mass7,mass8,mass9,mass10,x_non_negative])
problem.solve(solver="glpk")
problem.status
print("Result: {}".format(x.value))
print("Price: {}".format(problem.objective.value()[0]))
stop = time.time()
print(stop-start)

GLPK Simplex Optimizer, v4.65
35 rows, 25 columns, 75 non-zeros
      0: obj =   0.000000000e+00 inf =   6.000e+02 (5)
      8: obj =   2.500000000e+03 inf =   0.000e+00 (0)
*    27: obj =   1.850000000e+03 inf =   0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
Result: [ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 5.00e+01]
[ 0.00e+00]
[ 1.00e+02]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 5.00e+01]
[ 0.00e+00]
[ 1.00e+02]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+02]
[ 1.00e+02]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+02]

Price: 1850.0
0.5967159271240234


In [2]:
'''matrix: [[11  5  7  0  1]
[ 4  1  1  0  3]
[10 12  7  5 10]
[11 11  8 12  0]
[ 0  4  0  9 10]]"	P = ([0.0, 0.0, 0.69, 0.29, 0.02])	Q=([0.0, 0.0, 0.25, 0.43, 0.33])'''

'matrix: [[11  5  7  0  1]\n[ 4  1  1  0  3]\n[10 12  7  5 10]\n[11 11  8 12  0]\n[ 0  4  0  9 10]]"\tP = ([0.0, 0.0, 0.69, 0.29, 0.02])\tQ=([0.0, 0.0, 0.25, 0.43, 0.33])'

# Матричная игра
###### Вариант 17

In [3]:
import numpy as np
matrix = np.array([[11,  5,  7,  0,  1],
                   [ 4,  1,  1,  0,  3],
[10, 12,  7,  5, 10],
[11, 11,  8, 12,  0],
[ 0,  4,  0,  9, 10]])
P = [0.0, 0.0, 0.69, 0.29, 0.02]
Q = [0.0, 0.0, 0.25, 0.43, 0.33]

In [4]:
alpha = max(matrix.min(axis = 1))
betta = min(matrix.max(axis = 0))
print(alpha,betta)
Ha=0
for i in range(5):
    for j in range(5):
        Ha += matrix[i][j] * P[i] * Q[j]
print(Ha)

5 8
7.187799999999999


In [5]:
strat = [0] * 5
for i in range(5):
    for j in range(5):
        strat[j] += P[i]*matrix[i][j]
print(strat)

[10.09, 11.549999999999999, 7.15, 7.109999999999999, 7.1]
